apiVersion: v2
name: gitea-action-runner
description: A Helm chart for gitea action runner
type: application

version: 1.0.0
appVersion: "1.0.0"


# https://gitea.com/vquie/act_runner-helm/src/branch/main/templates/deployment.yaml
# https://gitea.com/gitea/act_runner/src/branch/main/examples/kubernetes/dind-docker.yaml