apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "gitea_action_runner.fullname" . }}
  labels:
    {{- include "gitea_action_runner.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "gitea_action_runner.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "gitea_action_runner.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "gitea_action_runner.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: runner
          command: ["sh", "-c", "while ! nc -z localhost 2376 </dev/null; do echo 'waiting for docker daemon...'; sleep 5; done; /sbin/tini -- /opt/act/run.sh"]
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: DOCKER_HOST
              value: tcp://localhost:2376
            - name: DOCKER_CERT_PATH
              value: /certs/client
            - name: DOCKER_TLS_VERIFY
              value: "1"
            - name: GITEA_INSTANCE_URL
              value: {{ .Values.act_runner.instance }}
            - name: GITEA_RUNNER_REGISTRATION_TOKEN
              valueFrom:
                secretKeyRef:
                  name: runner-secret
                  key: token

            - name: DOCKER_HOST
              value: "tcp://localhost:2375"
            - name: DOCKER_TLS_CERTDIR
              value: ""
            - name: ACT_INSTANCE
              value: {{ .Values.act_runner.instance }}
            - name: debug1
              value: {{ .Values.persistence.enabled }}
            - name: debug2
              value: {{ .Values.persistence.create }}
            - name: ACT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ include "gitea_action_runner.fullname" . }}-secret
                  key: act-runner-token
            - name: ACT_LABELS
              value: {{ join "," .Values.act_runner.labels }}
          volumeMounts:
            - name: docker-certs
              mountPath: /certs
            - name: data
              mountPath: /data
        - name: daemon
          securityContext:
            privileged: true
          image: docker:23.0.6-dind
          imagePullPolicy: IfNotPresent
          env:
            - name: DOCKER_DRIVER
              value: "overlay2"
            - name: DOCKER_TLS_CERTDIR
              value: /certs
          volumeMounts:
            - name: docker-certs
              mountPath: /certs
      volumes:
        - name: docker-certs
          emptyDir: {}
        {{- if .Values.persistence.enabled }}
        - name: data
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.claimName }}
        {{- else if not .Values.persistence.enabled }}
        - name: data
          emptyDir: {}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}