---
{{- $token := .Values.act_runner.token | required ".Values.act_runner.token is required." -}}
apiVersion: v1
kind: Secret
metadata:
  name: runner-secret
  labels:
    {{- include "gitea_action_runner.labels" . | nindent 4 }}
data:
  token: {{ .Values.act_runner.token | b64enc }}
