name: Release Charts Benji
run-name: ${{ gitea.actor }} is testing out Gitea Actions 🚀
# https://blog.gitea.io/2023/03/hacking-on-gitea-actions/

env:
  CHARTMUSEUM_URL: ${{ secrets.HELM_REPO_URL }}
  CHARTMUSEUM_URL1: ${{ secrets.CHARTMUSEUM_URL }}
  CHARTMUSEUM_REPO_NAME: benji
  # CHARTMUSEUM_USER: ${{ secrets.CHARTMUSEUM_USER }}
  # CHARTMUSEUM_PASSWORD:  ${{ secrets.CHARTMUSEUM_PASSWORD }}

on:
  push:
    branches:
      - main
    # paths:
    #   - 'charts/jellyfin/**'

jobs:
  Explore-Gitea-Actions:
    permissions:
      contents: write
      # runs-on: ubuntu-latest
    runs-on: ubuntu-latest
    # runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: https://github.com/azure/setup-helm@v3
        with:
          version: v3.11.2

      - name: Step 1 - Echo out a GitHub Actions Secret to the logs
        run: |
          echo "The GitHub Action Secret will be masked:  "
          echo ${{ secrets.CHARTMUSEUM_URL }}
          echo "Trick to echo GitHub Actions Secret:  "
          echo ${{secrets.CHARTMUSEUM_URL}} | sed 's/./& /g'

      - name: Helm version
        run: |
          helm version -c

      - name: Run changed-files with dir_names
        id: changed-files-dir-names
        uses: tj-actions/changed-files@v39.2.1
        with:
          files: charts/*
          sha: b3d2d9781cfa1e4566f2e6c4dde90512cf1cc392
          dir_names_max_depth: "2"
          dir_names: "true"

      - name: List all changed files
        run: |
          for file in ${{ steps.changed-files-dir-names.outputs.all_changed_and_modified_files }}; do
            echo "$file was changed"
          done

      - name: Add repo
        run: |
          if [[ $CHARTMUSEUM_REPO_NAME ]]; then
            echo ${CHARTMUSEUM_REPO_NAME}
            echo ${CHARTMUSEUM_URL}
            echo ${CHARTMUSEUM_URL1}
            echo "helm repo add ${CHARTMUSEUM_REPO_NAME} ${{ secrets.CHARTMUSEUM_URL }}"
            helm repo add ${CHARTMUSEUM_REPO_NAME} ${{ secrets.CHARTMUSEUM_URL }}
            # --username=${CHARTMUSEUM_USER} --password=${CHARTMUSEUM_PASSWORD}
          fi
      - name: Update and list repo
        run: |
          helm repo update
          helm search repo

      # - name: Run chart-testing (lint)
      #   if: steps.changed-files-dir-names.outputs.all_changed_and_modified_files_count > 0
      #   run: |
      #     for dir in ${{ steps.changed-files-dir-names.outputs.all_changed_and_modified_files }}; do
      #       echo "linting $dir"
      #       helm lint --quiet $dir
      #     done



      - name: Run chart-package (package)
        if: steps.changed-files-dir-names.outputs.all_changed_and_modified_files_count > 0
        run: |
          for dir in ${{ steps.changed-files-dir-names.outputs.all_changed_and_modified_files }}; do
            echo "linting $dir"
            helm package $dir
          done

      - run: echo "🍏 This job's status is ${{ job.status }}."