name: Release Charts Benji
run-name: ${{ gitea.actor }} is testing out Gitea Actions 🚀
# https://blog.gitea.io/2023/03/hacking-on-gitea-actions/

env:
  CHARTMUSEUM_URL: ${{ secrets.CHARTMUSEUM_URL }}
  REPO_NAME: benji
  # CHARTMUSEUM_USER: ${{ secrets.CHARTMUSEUM_USER }}
  # CHARTMUSEUM_PASSWORD:  ${{ secrets.CHARTMUSEUM_PASSWORD }}
  ACTIVE_CHARTS: ("jellyfin" "hello-world" )

on:
  push:
    branches:
      - main
    # paths:
    #   - 'charts/jellyfin/**'

jobs:
  Explore-Gitea-Actions:
    permissions:
      contents: write
      # runs-on: ubuntu-latest
    runs-on: ubuntu-latest
    # runs-on: ubuntu-20.04
    steps:
      - name: Clone git repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

        # Install helm
      - name: Set up Helm
        uses: https://github.com/azure/setup-helm@v3
        with:
          version: v3.13.0

        # install yq
      - name: Setup YQ
        uses: chrisdickinson/setup-yq@latest
        with:
          yq-version: v4.35.2

      - name: Versions on tools
        run: |
          helm version -c
          yq --version

      - name: Run changed-files with dir_names
        id: changed-files-dir-names
        uses: tj-actions/changed-files@v39.2.1
        with:
          files: charts/*
          sha: b3d2d9781cfa1e4566f2e6c4dde90512cf1cc392
          dir_names_max_depth: "2"
          dir_names: "true"

      - name: Setup helm chart repo
        if: steps.changed-files-dir-names.outputs.all_changed_and_modified_files_count > 0
        run: |
          if [[ $REPO_NAME ]]; then
            # echo ${REPO_NAME}
            # echo ${CHARTMUSEUM_URL}
            # echo ${CHARTMUSEUM_URL1}
            # echo "helm repo add ${REPO_NAME} ${{ secrets.CHARTMUSEUM_URL }}"
            helm repo add ${REPO_NAME} ${{ secrets.CHARTMUSEUM_URL }}
            helm repo update
            # --username=${CHARTMUSEUM_USER} --password=${CHARTMUSEUM_PASSWORD}
          fi

      - name: Set alpha and prerelease for modified charts if not main
        id: alphaRelease
        if: github.ref_name == 'main' && steps.changed-files-dir-names.outputs.all_changed_and_modified_files_count > 0
        run: |
          yq --version
          for dir in ${{ steps.changed-files-dir-names.outputs.all_changed_and_modified_files }}; do
            # Move in to chart dir
            cd "${{ gitea.workspace }}/${dir}"

            # Append alpha to release if not main
            sed -i '/^version: /s/$/-alpha/' Chart.yaml

            # Set prerelease to true if not main
            yq -i '(.annotations | select(has("artifacthub.io/prerelease"))."artifacthub.io/prerelease") |= "true"' Chart.yaml
          done

          # Go back to workspace main dir
          cd "${{ gitea.workspace }}"

      - name: Package changed charts
        if: steps.changed-files-dir-names.outputs.all_changed_and_modified_files_count > 0
        run: |
          for dir in ${{ steps.changed-files-dir-names.outputs.all_changed_and_modified_files }}; do
            cd "${{ gitea.workspace }}/${dir}"

            chartName=$(yq e '.name'  Chart.yaml)

            # Only run on some the charts for now
            if [[ $(echo ${ACTIVE_CHARTS[@]} | fgrep -w $chartName) ]]
            then
              helm package .

              chartVersion=$(yq e '.version'  Chart.yaml)
              chartPackage="${chartName}-${chartVersion}.tgz"

              echo "Branch: ${github.ref_name}"
              # if [[ "${ github.ref_name }" == 'main' ]] then
                # Delete an existing package of the current version prior to upload (mimicking --force)
                # curl -X DELETE -u "${_cm_user}:${_cm_pass}" "${CHARTMUSEUM_URL}/api/charts/${chartName}/${chartVersion}"
                curl -X DELETE "${CHARTMUSEUM_URL}/api/charts/${chartName}/${chartVersion}"
              # fi

              # Upload the package
              # curl --data-binary "@${chartPackage}" -u "${_cm_user}:${_cm_pass}" "${CHARTMUSEUM_URL}/api/charts"
              curl --data-binary "@${chartPackage}" "${CHARTMUSEUM_URL}/api/charts"

              # chartmuseum dont support pust at the momemt from oci url
              # helm push "${chartName}" "${REPO_NAME}"
            fi
          done

          # Back to workspace path
          cd ${{ gitea.workspace }}


      - run: echo "🍏 This job's status is ${{ job.status }}."

      # - name: List all changed files
      #   if: steps.changed-files-dir-names.outputs.all_changed_and_modified_files_count > 0
      #   run: |
      #     for file in ${{ steps.changed-files-dir-names.outputs.all_changed_and_modified_files }}; do
      #       echo "$file was changed"
      #     done

      # - name: Run chart-testing (lint)
      #   if: steps.changed-files-dir-names.outputs.all_changed_and_modified_files_count > 0
      #   run: |
      #     for dir in ${{ steps.changed-files-dir-names.outputs.all_changed_and_modified_files }}; do
      #       echo "linting $dir"
      #       helm lint --quiet $dir
      #     done
      # - run: echo "The name of your branch is ${{ gitea.ref }} and your repository is ${{ gitea.repository }}."
      # - run: echo "The name of your branch is ${{ gitea.ref_name }} and your repository is ${{ gitea.repository }}."


      # - name: Cat chart.yaml
      #   if: steps.changed-files-dir-names.outputs.all_changed_and_modified_files_count > 0
      #   run: |
      #     for dir in ${{ steps.changed-files-dir-names.outputs.all_changed_and_modified_files }}; do
      #       cat $dir/Chart.yaml
      #     done

      # - name: Step 1 - Echo out a GitHub Actions Secret to the logs
      #   run: |
      #     echo "The GitHub Action Secret will be masked:  "
      #     echo ${{ secrets.CHARTMUSEUM_URL }}
      #     echo "Trick to echo GitHub Actions Secret:  "
      #     echo ${{secrets.CHARTMUSEUM_URL}} | sed 's/./& /g'