name: Release Charts Benji
run-name: ${{ gitea.actor }} is testing out Gitea Actions 🚀
# https://blog.gitea.io/2023/03/hacking-on-gitea-actions/

on:
  push:
    branches:
      - main
#    paths:
#      - 'charts/home-assistant/**'

jobs:
  Explore-Gitea-Actions:
    permissions:
      contents: write
      # runs-on: ubuntu-latest
    runs-on: ubuntu-latest
    # runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0


      - name: Set up Helm
        uses: https://github.com/azure/setup-helm@v3
        with:
          version: v3.11.2


      # - name: prepare apt
      #   run: |
      #     ls -al /opt/hostedtoolcache/Python/

      # - name: prepare apt
      #   run: |
      #     apt-get -q update
      #     apt install -y lsb-release
      #     ls -al /opt

      - uses: https://github.com/actions/setup-python@v4
        with:
          python-version: '3.9'
          check-latest: true
          # cache: "pip"
        env:
          AGENT_TOOLSDIRECTORY: '/opt/github/actions-runner/_work/_tool'


      - name: Set up chart-testing
        uses: https://github.com/helm/chart-testing-action@v2.4.0

      - name: Run chart-testing (list-changed)
        id: list-changed
        run: |
          changed=$(ct list-changed --target-branch ${{ github.event.repository.default_branch }})
          if [[ -n "$changed" ]]; then
            echo "changed=true" >> "$GITHUB_OUTPUT"
          fi

      - name: Run chart-testing (lint)
        if: steps.list-changed.outputs.changed == 'true'
        run: ct lint --target-branch ${{ github.event.repository.default_branch }}

      - name: Create kind cluster
        if: steps.list-changed.outputs.changed == 'true'
        uses: https://github.com/helm/kind-action@v1.4.0

      - name: Run chart-testing (install)
        if: steps.list-changed.outputs.changed == 'true'
        run: ct install --target-branch ${{ github.event.repository.default_branch }}

      # - name: Configure Git
      #   run: |
      #     git config user.name "$GITHUB_ACTOR"
      #     git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
      # - name: Install Helm
      #   uses: azure/setup-helm@v3
      #   with:
      #     version: v3.10.0



      # - name: Push Helm Chart to ChartMuseum
      #   uses: bsord/helm-push@v4.2.0
      #   with:
      #     username: ${{ secrets.GITEA_USERNAME }}
      #     password: ${{ secrets.GITEA_TOKEN }}
      #     registry-url: https://gitea.newbenji.dk/api/packages/newbenji/helm/api/charts
      #     force: true
      #     chart-folder: 'charts/home-assistant/'

      # - name: Run chart-releaser
      #   uses: helm/chart-releaser-action@v1.5.0
      #   env:
      #     CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      #     # CR_SKIP_EXISTING: true
