
jenkins-x-crds:
  something: true

jx-pipelines-visualizer:
  fullnameOverride: jx-pipelines-visualizer
  config:
    pipelineTraceURLTemplate: https://grafana.newbenji.dk/explore?left=%5B%22now%22,%22now%22,%22Tempo%22,%7B%22query%22:%22{{.TraceID}}%22%7D%5D
  ingress:
    enabled: false 
    apiVersion: networking.k8s.io/v1
    annotations:
      # cert-manager.io/cluster-issuer: letsencrypt
      # kubernetes.io/ingress.class: nginx
      # kubernetes.io/tls-acme: 'true'
      # nginx.ingress.kubernetes.io/ssl-redirect: 'true'
      nginx.ingress.kubernetes.io/whitelist-source-range: 192.168.1.1/24
    labels: 
      benji: tester
    hosts:
      - jenkins-x.newbenji.dk
    tls: 
      enabled: false 
      secrets:
        si: si
#       secrets:
# #        b64encodedCertificate: false
# #        b64encodedCertificateKey: false
#         hosts:
#           jenkins-x.newbenji.dk
#         # secretName: artifacthub-tls-secret

jx-preview:
  something: true

# override dosnt work
jx-build-controller:
  fullnameOverride: jx-build-controller