piVersion: v1
kind: Secret
metadata:
  name: {{ include "hello-world.fullname" . }}-vscode
  labels:
    {{- include "hello-world.labels" . | nindent 4 }}
type: Opaque
data:
  test: {{ .Values.secret.test | b64enc }}
  password: {{ .Values.secret.password | b64enc | quote }}
