apiVersion: v1
kind: ConfigMap
metadata:
  name: config-telegram-bot
  labels:
    app.kubernetes.io/name: {{ include "home-assistant.name" . }}
    helm.sh/chart: {{ include "home-assistant.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  telegram_bot.yaml: | {{ include "home-assistant.telegram_bot" . | nindent 4 }}
