apiVersion: v1
kind: ConfigMap
metadata:
  name: config-scripts
  labels:
    {{- include "home-assistant.labels" . | nindent 4 }}
data:
  scripts.yaml: | {{ include "home-assistant.scripts" . | nindent 4 }}
