apiVersion: apps/v1
kind: Deployment
metadata:
  name: wyoming-whisper
  labels:
    {{- include "home-assistant.labels" . | nindent 4 }}
    aapp.kubernetes.io/component: whisper
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "home-assistant.selectorLabelsWhisper" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "home-assistant.selectorLabelsWhisper" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "home-assistant.serviceAccountName" . }}
      # strategy:
      #   type: Recreate
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      dnsPolicy: {{ .Values.dnsPolicy }}
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: whisper
      containers:
        - name: wyoming-whisper
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "rhasspy/wyoming-whisper:1.0.0"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - --model
            - small
          env:
            - name: TZ
              value: Europe/Copenhagen
          volumeMounts:
            - mountPath: /data
              name: data
          ports:
            - name: whisper
              containerPort: 10300
              protocol: TCP
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}

      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: whisper
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  volumeMode: Filesystem