apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "home-assistant.fullname" . }}
  labels:
    {{- include "home-assistant.labels" . | nindent 4 }}
    app.kubernetes.io/component: home-assistant
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "home-assistant.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "home-assistant.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "home-assistant.serviceAccountName" . }}
      # strategy:
      #   type: Recreate
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      hostNetwork: {{ .Values.hostNetwork }}
      dnsPolicy: {{ .Values.dnsPolicy }}
      volumes:
        - name: config
          {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.existingClaim | default (include "home-assistant.fullname" .) }}
          {{- else }}
          emptyDir: { }
          {{- end }}
          {{- if .Values.persistence.additionalVolumes }}
            {{- .Values.persistence.additionalVolumes | toYaml | nindent 8}}
          {{- end }}
        - name: passwords
          secret:
            secretName: passwords
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
            - mountPath: /config
              name: config
            {{- if .Values.persistence.additionalMounts }}
              {{- .Values.persistence.additionalMounts | toYaml | nindent 12 }}
            {{- end }}
            - name: passwords
              mountPath: /config/passwords
              readOnly: true
          ports:
            - name: http
              containerPort: 8123
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
        {{- if .Values.vscode.enabled }}
        - name: vscode
          image: "{{ .Values.vscode.image.repository }}:{{ .Values.vscode.image.tag }}"
          imagePullPolicy: {{ .Values.vscode.image.pullPolicy }}
          workingDir: {{ .Values.vscode.hassConfig }}
          args:
            # - --allow-http
            - --port={{ .Values.vscode.service.port }}
            {{- if not ( .Values.vscode.password ) }}
            - --auth=none
            {{- end }}
            {{- if .Values.vscode.vscodePath }}
            - --extensions-dir={{ .Values.vscode.vscodePath }}
            - --user-data-dir={{ .Values.vscode.vscodePath }}
            {{- end }}
          ports:
            - name: vscode
              containerPort: {{ .Values.vscode.service.port }}
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: vscode
            initialDelaySeconds: 30
          readinessProbe:
            tcpSocket:
              port: vscode
            initialDelaySeconds: 15
          env:
            {{- if .Values.vscode.password }}
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ template "home-assistant.fullname" . }}-vscode
                  key: password
            {{- end }}
            {{- range $key, $value := .Values.vscode.extraEnv }}
            - name: {{ $key }}
              value: {{ $value }}
            {{- end }}
          volumeMounts:
          - mountPath: /config
            name: config
          {{- if .Values.usePodSecurityContext }}
          securityContext:
            runAsUser: {{ default 0 .Values.runAsUser }}
          {{- if and ( .Values.runAsUser ) ( .Values.fsGroup ) }}
          {{- if not ( eq .Values.runAsUser 0.0) }}
            fsGroup: {{ .Values.fsGroup }}
          {{- end }}
          {{- end }}
          {{- end }}
          resources:
            {{ toYaml .Values.vscode.resources | indent 12 }}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
