{{- if and .Values.matterServer.enabled .Values.matterServer.persistence.enabled (not .Values.matterServer.persistence.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "home-assistant.matterServerFullname" . }}
  labels:
    {{- include "home-assistant.labelsMatterServer" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.matterServer.persistence.accessMode | quote }}
  {{- if .Values.matterServer.persistence.storageClass }}
  storageClassName: {{ .Values.matterServer.persistence.storageClass | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.matterServer.persistence.size | quote }}
{{- end }}
