apiVersion: v1
kind: Secret
metadata:
  name: secrets
  labels:
    app.kubernetes.io/name: {{ include "home-assistant.name" . }}
    helm.sh/chart: {{ include "home-assistant.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  postgresql: {{ "postgresql://homeassistant:theise8aeGephuuChiTh@postgresql-service.pg.svc.cluster.local/homeassistant" | b64enc }}
  s: {{ .Values.postgresql.connection | b64enc }}
