{{- if and .Values.whisper.enabled .Values.whisper.persistence.enabled (not .Values.whisper.persistence.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "home-assistant.whisperFullname" . }}
  labels:
    {{- include "home-assistant.labelsWhisper" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.whisper.persistence.accessMode | quote }}
  {{- if .Values.whisper.persistence.storageClass }}
  storageClassName: {{ .Values.whisper.persistence.storageClass | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.whisper.persistence.size | quote }}
{{- end }}
