name: actions-test
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - test-branch
  # schedule:
    # - cron: '* * * *'
jobs:
  print-hello:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello, world"