name: Build alpha helm charts
run-name: ${{ github.actor }} is testing new versions of charts 🚀
on:
  push:
    branches-ignore:
      - main
  # pull_request:
  #   branches:
  #     - main
  #   types:
  #     - closed


jobs:
  detect-changed-folders:
    runs-on: charts
    outputs:
      folders: ${{ steps.get_changed_dirs.outputs.all_changed_and_modified_files }}
    steps:
      - uses: ConorMacBride/install-package@v1
        with:
          apt: git

      - name: Clone git repo
        uses: actions/checkout@v4
        with:
          fetch-depth: '0'
          fetch-tags: 'true'

      # - name: Print info
      #   run: echo "'${{ github.ref_name }}' was pushed by '${{ github.event.pusher.name }}', '${{ github.base_ref }}' "

      - name: Get origin commit and branch
        id: git-branch
        run: |
          ORIGIN_BRANCH="refs/remotes/origin/$(git branch -r | tail -n 1 | cut -d "/" -f2)"
          MAIN_COMMIT=$(git merge-base origin/main ${ORIGIN_BRANCH})
          echo "Origin branch: ${ORIGIN_BRANCH}"
          echo "Main commit: ${MAIN_COMMIT}"
          echo "ORIGIN_BRANCH=${ORIGIN_BRANCH}" >> $GITHUB_OUTPUT
          echo "ORIGIN_SHA=${MAIN_COMMIT}" >> $GITHUB_OUTPUT

      - name: Run changed-files with dir_names
        id: get_changed_dirs
        uses: tj-actions/changed-files@v44
        with:
          matrix: true
          # json: true
          files: charts/**
          sha: "${{ steps.git-branch.outputs.ORIGIN_SHA }}"
          dir_names_max_depth: "2"
          dir_names: true

  build-chart:
    needs: [detect-changed-folders]
    runs-on: charts
    strategy:
      matrix:
        files: ${{ fromJSON(needs.detect-changed-folders.outputs.folders) }}
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v4

        # Install helm
      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.13.3

      - uses: ConorMacBride/install-package@v1
        with:
          apt: git curl

      - name: Setup YQ
        uses: chrisdickinson/setup-yq@latest
        with:
          yq-version: v4.35.2

      - name: Install Dependencies
        run: |
          echo ${{ matrix.chartfolder }}

      - name: Add chart repo
        env:
          _CM_USER: ${{ secrets.CHARTMUSEUM_USERNAME }}
          _CM_PASS: ${{ secrets.CHARTMUSEUM_PASSWORD }}
          _REPO_URL: ${{ vars.HELM_REPOSITORY_URL }}
        run: |
          echo "Add repo"
          # # Upload the package since helm push dosnt work on chartmuseum yet
          # # prepared the command for user password
          helm plugin install https://github.com/chartmuseum/helm-push
          helm repo add --username "${_CM_USER}" --password "${_CM_PASS}" encode "${_REPO_URL}"

      - name: Enter chart dir
        run: |
          cd ${{ matrix.files }}


      - name: Set alpha and prerelease for modified charts if not main
        id: alphaRelease
        # if: github.ref_name != 'main' && steps.changed-files-dir-names.outputs.all_changed_and_modified_files_count > 0
        # if: github.ref_name != 'main' && steps.changed-files-dir-names.outputs.all_changed_and_modified_files_count > 0
        if: github.ref_name != 'main'
        run: |
          pwd
          cd ${{ matrix.files }}
          pwd
          sed -i '/^version: /s/$/-alpha/' Chart.yaml
          yq -i '(.annotations | select(has("artifacthub.io/prerelease"))."artifacthub.io/prerelease") |= "true"' Chart.yaml

      - name: Lint packages
        run: |
          pwd
          cd ${{ matrix.files }}
          if [ -f "values-lint.yaml" ]; then
            helm dependency build .
            helm lint -f values.yaml -f values-lint.yaml . --with-subcharts
          else
            helm lint -f values.yaml . --with-subcharts
          fi

      - name: Package chart and upload
        id: package
        env:
          _CM_USER: ${{ secrets.CHARTMUSEUM_USERNAME }}
          _CM_PASS: ${{ secrets.CHARTMUSEUM_PASSWORD }}
          _REPO_URL: ${{ vars.HELM_REPOSITORY_URL }}
        run: |
          cd ${{ matrix.files }}
          chartName=$(yq e '.name' Chart.yaml)
          chartVersion=$(yq e '.version' Chart.yaml)
          chartPackage="${chartName}-${chartVersion}.tgz"

          helm dependency build .
          helm package .

          # # only if not branch main
          if [ "${{ github.ref_name }}" != "main" ]; then
            echo "Since not in main, we delete a package first"
            # Delete an existing package of the current version prior to upload (mimicking --force)

            # curl -X DELETE -u "${_CM_USER}:${_CM_PASS}" "${_REPO_URL}/api/charts/${chartName}/${chartVersion}"
            # curl -X DELETE "${CHARTMUSEUM_URL}/api/charts/${chartName}/${chartVersion}"
          fi

          # echo "Upload chart"
          # # # Upload the package since helm push dosnt work on chartmuseum yet
          # # # prepared the command for user password
          # helm plugin install https://github.com/chartmuseum/helm-push
          # helm repo add --username "${_CM_USER}" --password "${_CM_PASS}" encode "${_REPO_URL}"
          helm cm-push --force . encode

          # curl --data-binary "@${chartPackage}" -u "${_CM_USER}:${_CM_PASS}" "${_REPO_URL}/api/charts"
          # curl --data-binary "@${chartPackage}" "${CHARTMUSEUM_URL}/api/charts"

          # # chartmuseum dont support pust at the momemt from oci url
          # # helm push "${chartName}" "${REPO_NAME}"