name: Lint and Test Charts

on:
  push:
    branches-ignore:
      - main

jobs:
  lint-test:
    runs-on: charts
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v4.2.0
        with:
          version: v3.17.0

      - uses: actions/setup-python@v5.3.0
        with:
          python-version: '3.x'
          check-latest: true

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.7.0

      - name: Setup YQ
        uses: chrisdickinson/setup-yq@latest
        with:
          yq-version: v4.35.2



      - name: Run chart-testing (list-changed)
        id: list-changed
        run: |
          changed=$(ct --chart-dirs charts list-changed --target-branch ${{ github.event.repository.default_branch }})
          if [[ -n "$changed" ]]; then
            echo "changed=true" >> "$GITHUB_OUTPUT"
          fi

      - name: Select CT configgile
        id: ct_config
        run: |
          if [[ $GITHUB_REF_NAME == 'main' ]]; then
            echo "CT_CONFIG_FILE=ct.yaml" >> $GITHUB_OUTPUT
          else
            echo "CT_CONFIG_FILE=ct-alpha.yaml" >> $GITHUB_OUTPUT
          fi


      - name: Mark chart as alpha
        id: mark-charts-alpha
        run: |
          changed=$(ct --config ${{ steps.ct_config.outputs.CT_CONFIG_FILE }} list-changed)
          while IFS= read -r line ; do
            cd $(echo $line | tr -d '\r')
            sed -i '/^version: /s/$/-alpha/' Chart.yaml
            yq -i '(.annotations | select(has("artifacthub.io/prerelease"))."artifacthub.io/prerelease") |= "true"' Chart.yaml
            cd ${{ github.workspace }}
          done <<< "$changed"




      - name: Create values-lint.yaml
        id: values-lint
        run: |
          changed=$(ct --config ${{ steps.ct_config.outputs.CT_CONFIG_FILE }} list-changed)
          while IFS= read -r line ; do
            cd $(echo $line | tr -d '\r')
            mkdir -p ci
            # if ! [ -e "ci/values-lint.yaml" ] ; then
            #   mkdir -p ci
            #   touch "lint-values.yaml"
            #   ls -al
            # fi
            cd ${{ github.workspace }}

          done <<< "$changed"

      - name: install helm unittests
        if: steps.list-changed.outputs.changed == 'true'
        run: |
          helm env
          # renovate: datasource=github-tags depName=helm-unittest/helm-unittest
          helm plugin install https://github.com/helm-unittest/helm-unittest.git

      - name: Run chart-testing (lint)
        if: steps.list-changed.outputs.changed == 'true'
        run: |
          ct lint --config ${{ steps.ct_config.outputs.CT_CONFIG_FILE }}

      - name: Create kind cluster
        if: steps.list-changed.outputs.changed == 'true'
        uses: helm/kind-action@v1.12.0

      - name: Run chart-testing (install)
        if: steps.list-changed.outputs.changed == 'true'
        run: |
          # kubectl get nodes
          # kubectl get ns
          ct install --config ${{ steps.ct_config.outputs.CT_CONFIG_FILE }} --debug
          ls -al
