name: Detect modified charts
run-name: ${{ github.actor }} detecting which charts have been modified 🚀


on:
  workflow_call:
    outputs:
      folders:
        description: "Which paths under charts have been modified"
        value: ${{ jobs.detect-changed-folders.outputs.folders }}
      folderstest:
        description: "Which paths under charts have been modified"
        value: ${{ jobs.detect-changed-folders.outputs.folders }}

      tester:
        description: "Which paths under charts have been modified"
        value: ${{ jobs.detect-changed-folders.outputs.tester }}
    inputs:
      config-path:
        required: true
        type: string
    secrets:
      HELM_REPOSITORY_URL:
        required: true

jobs:
  detect-changed-folders:
    runs-on: ${{ vars.RUNNER }}
    outputs:
      folders: ${{ steps.get_changed_dirs.outputs.all_changed_and_modified_files }}
      tester: ${{ steps.tester_one.outputs.tester || steps.tester_two.outputs.tester }}
      folderstest: ${{  steps.get_changed_dirs_pull.outputs.all_changed_and_modified_files ||  steps.get_changed_dirs.outputs.all_changed_and_modified_files }}
    steps:
      - uses: ConorMacBride/install-package@v1
        with:
          apt: git

      - name: Clone git repo
        uses: actions/checkout@v4
        with:
          fetch-depth: '0'
          fetch-tags: 'true'

      - name: Get origin commit and branch
        id: git-branch
        run: |
          ORIGIN_BRANCH="refs/remotes/origin/$(git branch -r | tail -n 1 | cut -d "/" -f2)"
          MAIN_COMMIT=$(git merge-base origin/main ${ORIGIN_BRANCH})
          echo "Origin branch: ${ORIGIN_BRANCH}"
          echo "Main commit: ${MAIN_COMMIT}"
          echo "ORIGIN_BRANCH=${ORIGIN_BRANCH}" >> $GITHUB_OUTPUT
          echo "ORIGIN_SHA=${MAIN_COMMIT}" >> $GITHUB_OUTPUT

      - name: Run changed-files with dir_names
        id: get_changed_dirs
        uses: tj-actions/changed-files@v45
        with:
          matrix: true
          # json: true
          files: charts/**
          sha: "${{ steps.git-branch.outputs.ORIGIN_SHA }}"
          dir_names_max_depth: "2"
          dir_names: true

      - name: Run changed-files with dir_names
        id: get_changed_dirs_pull
        uses: tj-actions/changed-files@v45
        with:
          matrix: true
          # json: true
          files: charts/**
          # sha: "${{ steps.git-branch.outputs.ORIGIN_SHA }}"
          dir_names_max_depth: "2"
          dir_names: true

      - name: List all added files
        run: |
          for file in ${{ steps.get_changed_dirs.outputs.all_changed_and_modified_files }}; do
            echo "$file was modified."
          done
          for file in ${{ steps.get_changed_dirs_pull.outputs.all_changed_and_modified_files }}; do
            echo "$file was modified."
          done

      - name: TEST output 1
        if: steps.get_changed_dirs_pull.outputs.any_changed
        id: tester_one
        run: |
          echo "tester=1" >> $GITHUB_OUTPUT

      - name: TEST output 2
        if: steps.get_changed_dirs.outputs.any_changed
        id: tester_two
        run: |
          echo "tester=2" >> $GITHUB_OUTPUT


      # - name: list modfied
      #   if: steps.get_changed_dirs.outputs.any_changed == 'true'
      #   run: |
      #     for file in ${{ steps.get_changed_dirs.outputs.all_changed_files  }}; do
      #       echo "$file was modified."
      #     done